[target.wasm32-unknown-emscripten]
rustflags = [
  "-Clink-arg=--no-entry",
  # "-Clink-arg=-O1",
  "-Clink-arg=-O0",
  "-Clink-arg=-sASSERTIONS=2",
  "-Clink-arg=-sSAFE_HEAP=1",
  "-Clink-arg=-sSTACK_OVERFLOW_CHECK=2",
  "-Clink-arg=-sDEMANGLE_SUPPORT=1",
  "-Clink-arg=-g",
  "-Clink-arg=-sSTACK_SIZE=1024MB",
  "-Clink-arg=-sINITIAL_MEMORY=4294967296",
  # "-Clink-arg=-sMAXIMUM_MEMORY=4294967296",
  # "-Clink-arg=-sALLOW_MEMORY_GROWTH=1",
  # "-Clink-arg=-sEMULATE_FUNCTION_POINTER_CASTS=1",
  "-Clink-arg=-sSIDE_MODULE=2",
  "-Clink-arg=-sUSE_PTHREADS=1",
  "-Clink-arg=-sEXPORT_ALL=1",
  # "-Clink-arg=--shared-memory",
  "-Ctarget-feature=+atomics,+bulk-memory,+mutable-globals"
]
