[package]
name = "hello_gdext"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
debug = true

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master", default-features = false }
