[package]
name = "hello_gdext"
version = "0.1.0"
edition = "2021"
rust-version = "1.74.1"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master", default-features = false, features = ["custom-godot"] }
